name: hello-world-action
on: push
jobs:
  hello_world_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: récuperation du code
        uses: actions/checkout@v4
      - name: Hello World
        run: echo "hello world"