name: hello-world-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "hello world"
      - run: npm install -g bats
      - run: bats -y